runtime: nodejs14

env: standard
# service: frontend
handlers:
    - url: /static
      static_dir: build/static
    - url: /(.*\.(json|ico|js|png|jpeg))$
      static_files: build/\1
      upload: build/.*\.(json|ico|js|png|jpeg)$
    - url: .*
      static_files: build/index.html
      upload: build/index.html